service_name: '5c39bc6c-7921-4296-a6b6-5445436b2c6c'

http:
  url: http://0.0.0.0:9000
  cors:
    access_control_allow_headers:
      - Content-Type
      - Cache-Control
      - Authorization
      - X-Total-Count
    access_control_allow_origin:
      - https://go2.uiscom.ru

uc_flow_node:
  register_on_start: false
  execute_view_queue_size: 500
  execute_view_workers: 5
  private_url: https://0689-94-25-181-111.ngrok-free.app
  public_url: https://0689-94-25-181-111.ngrok-free.app
  uc_flow:
    domain: https://uc-flow-v2-pp-api.comagic.ru
    jwt_secret: asdxczcxzv